# Generated by Django 5.2.8 on 2025-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_wallet_currency_remove_wallet_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='customuser',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Забанен до'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Премиум до'),
        ),
    ]
