# Generated by Django 5.2.8 on 2025-11-23 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_currency_options_alter_globallocation_name_and_more'),
        ('users', '0003_remove_customuser_is_banned_customuser_banned_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.sublocation', verbose_name='Текущая локация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
    ]
