# Generated by Django 5.2.8 on 2025-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_sub_location_alter_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_filename',
            field=models.CharField(default='elf_1.svg', max_length=100, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10, verbose_name='Пол'),
        ),
    ]
