# Generated by Django 5.2.8 on 2025-11-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_avatar_filename_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_filename',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(choices=[], default='male/elf_1.svg', max_length=100, verbose_name='Аватар'),
        ),
    ]
