# Generated by Django 5.2.8 on 2025-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_avatar_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(choices=[('male/ork_1.jpg', 'Мужской — Ork 1'), ('male/ork_2.jpg', 'Мужской — Ork 2'), ('male/ork_3.jpg', 'Мужской — Ork 3'), ('female/avatar.svg', 'Женский — Avatar'), ('female/human_1.jpg', 'Женский — Human 1'), ('female/human_2.jpg', 'Женский — Human 2')], default='male/elf_1.svg', max_length=100, verbose_name='Аватар'),
        ),
    ]
