# Generated by Django 5.2.8 on 2025-11-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sub_location',
            new_name='current_location',
        ),
    ]
