# Generated by Django 5.2.8 on 2025-11-26 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_globallocation_is_city'),
        ('users', '0008_rename_sub_location_customuser_current_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_global_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.globallocation', verbose_name='Текущая глобальная локация'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_sublocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.sublocation', verbose_name='Текущая саблокация'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_destination', to='game.sublocation', verbose_name='Перемещение в'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
