# Generated by Django 5.2.8 on 2025-11-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='travel_duration_seconds',
        ),
    ]
