# Generated by Django 5.2.8 on 2025-11-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_travel_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='travel_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
