# Generated by Django 5.2.8 on 2025-11-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='defense',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dexterity',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spirit',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stamina',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='willpower',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
