# Generated by Django 5.2.8 on 2025-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_defense_customuser_dexterity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='item_slots',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
