# Generated by Django 5.2.8 on 2025-11-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_item_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='item_slots',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
