# Generated by Django 5.2.8 on 2025-11-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_item_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='defense',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dexterity',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Ловкость'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='item_slots',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='Слоты инвентаря'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spirit',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Дух'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stamina',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Выносливость'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='willpower',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Воля'),
        ),
    ]
