# Generated by Django 5.2.8 on 2025-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_defense_alter_customuser_dexterity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='intelligence',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Интеллект'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='strength',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Сила'),
        ),
    ]
