# Generated by Django 5.2.8 on 2025-11-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_intelligence_customuser_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='luck',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Удача'),
        ),
    ]
