# Generated by Django 5.2.8 on 2025-11-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_luck'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_hp',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущее здоровье'),
        ),
    ]
