# Generated by Django 5.2.8 on 2025-11-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_current_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_fight_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего нападения'),
        ),
    ]
