# Generated by Django 5.2.8 on 2025-11-23 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'Валюты',
                'default_related_name': 'currecny',
            },
        ),
        migrations.CreateModel(
            name='GlobalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'глобальная локация',
                'verbose_name_plural': 'Глобальные локации',
                'default_related_name': 'globallocations',
            },
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название внутренней локации')),
                ('slug', models.SlugField()),
                ('global_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sublocations', to='game.globallocation')),
            ],
            options={
                'verbose_name': 'внутренняя локация',
                'verbose_name_plural': 'Внутренние локации',
                'default_related_name': 'sublocations',
            },
        ),
        migrations.CreateModel(
            name='PlayerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
                ('sublocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.sublocation')),
            ],
            options={
                'verbose_name': 'локация игрока',
                'verbose_name_plural': 'Локации игроков',
                'default_related_name': 'playerlocations',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'кошелек',
                'verbose_name_plural': 'Кошельки',
                'default_related_name': 'wallets',
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
