# Generated by Django 5.2.8 on 2025-11-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'default_related_name': 'currencies', 'verbose_name': 'валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterField(
            model_name='globallocation',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='globallocation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playerlocation',
            name='sublocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.sublocation'),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Название внутренней локации'),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='sublocation',
            unique_together={('global_location', 'slug')},
        ),
    ]
