# Generated by Django 5.2.8 on 2025-11-23 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_currency_options_alter_globallocation_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sublocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название внутренней локации'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Персонаж'),
        ),
        migrations.AlterUniqueTogether(
            name='sublocation',
            unique_together={('global_location', 'name')},
        ),
        migrations.DeleteModel(
            name='PlayerLocation',
        ),
    ]
