# Generated by Django 5.2.8 on 2025-11-23 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_sublocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globallocation',
            options={'default_related_name': 'globallocations', 'verbose_name': ('глобальная локация',), 'verbose_name_plural': 'Глобальные локации'},
        ),
        migrations.AlterModelOptions(
            name='sublocation',
            options={'default_related_name': 'sublocations', 'verbose_name': ('внутренняя локация',), 'verbose_name_plural': 'Внутренние локации'},
        ),
        migrations.AlterField(
            model_name='globallocation',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Название локации'),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='global_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sublocations', to='game.globallocation', verbose_name='Глобальная локация'),
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('strength', models.PositiveIntegerField(default=5)),
                ('agility', models.PositiveIntegerField(default=5)),
                ('vitality', models.PositiveIntegerField(default=5)),
                ('intelligence', models.PositiveIntegerField(default=5)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Тип монстра',
                'verbose_name_plural': 'Типы монстров',
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.AddField(
            model_name='sublocation',
            name='monsters',
            field=models.ManyToManyField(blank=True, related_name='locations', to='game.monster', verbose_name='Монстры на локации'),
        ),
    ]
