# Generated by Django 5.2.8 on 2025-11-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_globallocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(help_text="Уникальный код: 'rusty_sword', 'orc_fang'", max_length=30, unique=True)),
                ('item_type', models.CharField(choices=[('JUNK', 'Хлам'), ('RESOURCE', 'Ресурс'), ('ORE', 'Руда'), ('ARMOR', 'Броня'), ('WEAPON', 'Оружие'), ('AMULET', 'Амулет'), ('POTION', 'Зелье'), ('CONSUMABLE', 'Используемый предмет'), ('QUEST', 'Квестовый')], max_length=20, verbose_name='Тип предмета')),
                ('slot', models.CharField(blank=True, choices=[('HEAD', 'Голова'), ('CHEST', 'Тело'), ('HANDS', 'Руки'), ('LEGS', 'Ноги'), ('FEET', 'Обувь'), ('MAIN_HAND', 'Основная рука'), ('OFF_HAND', 'Вторая рука'), ('NECK', 'Шея (амулет)'), ('FINGER', 'Палец (кольцо)'), ('WAIST', 'Пояс (амулет)'), ('EAR', 'Ухо (серьга)')], help_text='Заполняется только для брони, оружия, амулетов', max_length=20, verbose_name='Слот экипировки')),
                ('strength_bonus', models.IntegerField(default=0)),
                ('agility_bonus', models.IntegerField(default=0)),
                ('vitality_bonus', models.IntegerField(default=0)),
                ('intelligence_bonus', models.IntegerField(default=0)),
                ('is_stacked', models.BooleanField(default=True, help_text='Можно ли складывать в стак (хлам, ресурсы, зелья)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
