# Generated by Django 5.2.8 on 2025-11-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.PositiveIntegerField(default=1, help_text='Стоимость продажи в магазин', verbose_name='Базовая стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, help_text='Уникальный код (генерируется автоматически)', max_length=30, unique=True),
        ),
    ]
