# Generated by Django 5.2.8 on 2025-11-23 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_item_cost_alter_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agility_bonus',
            field=models.IntegerField(default=0, verbose_name='Ловкость'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, help_text='Уникальный код (генерируется автоматически)', max_length=30, unique=True, verbose_name='Код предмета'),
        ),
        migrations.AlterField(
            model_name='item',
            name='intelligence_bonus',
            field=models.IntegerField(default=0, verbose_name='Интеллект'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='strength_bonus',
            field=models.IntegerField(default=0, verbose_name='Сила'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vitality_bonus',
            field=models.IntegerField(default=0, verbose_name='Живучесть'),
        ),
        migrations.CreateModel(
            name='MonsterDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('CURRENCY', 'Валюта'), ('ITEM', 'Предмет')], max_length=10, verbose_name='Тип предмета')),
                ('min_amount', models.PositiveIntegerField(default=1, verbose_name='Минимальное кол-во')),
                ('max_amount', models.PositiveIntegerField(default=1, verbose_name='Максимальное кол-во')),
                ('chance_percent', models.DecimalField(decimal_places=2, help_text='Вероятность выпадения в процентах (0.00–100.00)', max_digits=5, verbose_name='Шанс выпадения')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.currency', verbose_name='Валюта')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='game.monster', verbose_name='Монстр')),
            ],
            options={
                'verbose_name': 'Дроп монстра',
                'verbose_name_plural': 'Дропы монстров',
            },
        ),
    ]
