# Generated by Django 5.2.8 on 2025-11-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_item_agility_bonus_alter_item_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monsterdrop',
            options={'verbose_name': 'Дроп с монстра', 'verbose_name_plural': 'Дропы с монстров'},
        ),
    ]
