# Generated by Django 5.2.8 on 2025-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_monsterdrop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='globallocation',
            name='description',
            field=models.TextField(blank=True, default='Здесь еще нет описания, возможно когда-то появится', verbose_name='Описание локации'),
        ),
    ]
