# Generated by Django 5.2.8 on 2025-11-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_globallocation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='globallocation',
            name='is_city',
            field=models.BooleanField(blank=True, default=False, verbose_name='Это город?'),
        ),
    ]
