# Generated by Django 5.2.8 on 2025-11-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_globallocation_is_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='globallocation',
            name='distance_to_the_city',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Расстояние до города'),
        ),
        migrations.AddField(
            model_name='sublocation',
            name='distance_to_location_start',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Расстояние до входа в локацию'),
        ),
    ]
