# Generated by Django 5.2.8 on 2025-11-26 08:28

from django.db import migrations, models

import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_globallocation_distance_to_the_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.monster_avatar_path, verbose_name='Аватар'),
        ),
    ]
