# Generated by Django 5.2.8 on 2025-11-26 12:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_monster_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='agility_bonus',
        ),
        migrations.RemoveField(
            model_name='item',
            name='intelligence_bonus',
        ),
        migrations.RemoveField(
            model_name='item',
            name='strength_bonus',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vitality_bonus',
        ),
        migrations.AddField(
            model_name='item',
            name='defense',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='dexterity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='intelligence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='spirit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stamina',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='strength',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='willpower',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strength_bonus', models.SmallIntegerField(default=0)),
                ('defense_bonus', models.SmallIntegerField(default=0)),
                ('dexterity_bonus', models.SmallIntegerField(default=0)),
                ('stamina_bonus', models.SmallIntegerField(default=0)),
                ('intelligence_bonus', models.SmallIntegerField(default=0)),
                ('spirit_bonus', models.SmallIntegerField(default=0)),
                ('willpower_bonus', models.SmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Шаблон предмета')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Уникальный экземпляр предмета',
                'verbose_name_plural': 'Уникальные экземпляры предметов',
            },
        ),
        migrations.CreateModel(
            name='ItemStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол-во')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Предмет')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Стек предметов',
                'verbose_name_plural': 'Стеки предметов',
                'unique_together': {('owner', 'item')},
            },
        ),
    ]
