# Generated by Django 5.2.8 on 2025-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_item_agility_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание монстра'),
        ),
        migrations.AddField(
            model_name='sublocation',
            name='description',
            field=models.TextField(blank=True, default='Здесь еще нет описания, возможно когда-то появится', verbose_name='Описание саблокации'),
        ),
        migrations.AlterField(
            model_name='globallocation',
            name='description',
            field=models.TextField(blank=True, default='Здесь еще нет описания, возможно когда-то появится', verbose_name='Описание глобальной локации'),
        ),
    ]
