# Generated by Django 5.2.8 on 2025-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_monster_description_sublocation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globallocation',
            name='max_level',
            field=models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Максимальный уровень локации'),
        ),
        migrations.AddField(
            model_name='globallocation',
            name='min_level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Минимальный уровень локации'),
        ),
        migrations.AddField(
            model_name='sublocation',
            name='max_level',
            field=models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Максимальный уровень локации'),
        ),
        migrations.AddField(
            model_name='sublocation',
            name='min_level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Минимальный уровень локации'),
        ),
    ]
