# Generated by Django 5.2.8 on 2025-11-27 03:03

from django.db import migrations, models

import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_globallocation_max_level_globallocation_min_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='agility',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='vitality',
        ),
        migrations.AddField(
            model_name='item',
            name='item_slots',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.item_logo_path, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='item',
            name='luck',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='defense',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Защита'),
        ),
        migrations.AddField(
            model_name='monster',
            name='dexterity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ловкость'),
        ),
        migrations.AddField(
            model_name='monster',
            name='spirit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дух'),
        ),
        migrations.AddField(
            model_name='monster',
            name='stamina',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Выносливость'),
        ),
        migrations.AddField(
            model_name='monster',
            name='willpower',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Воля'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='intelligence',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Интеллект'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='strength',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сила'),
        ),
    ]
