# Generated by Django 5.2.8 on 2025-11-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='Здесь еще нет описания, возможно когда-то появится', verbose_name='Описание предмета'),
        ),
    ]
