# Generated by Django 5.2.8 on 2025-11-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_iteminstance_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sellable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='min_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Мин. уровень игрока'),
        ),
    ]
