# Generated by Django 5.2.8 on 2025-11-28 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('game', '0020_item_is_sellable_item_min_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sublocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='game.sublocation')),
            ],
        ),
    ]
