# Generated by Django 5.2.8 on 2025-11-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_activitylink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='Здесь еще нет описания, возможно когда-то появится', verbose_name='Описание предмета')),
                ('item_type', models.CharField(choices=[('JUNK', 'Хлам'), ('RESOURCE', 'Ресурс'), ('ORE', 'Руда'), ('ARMOR', 'Броня'), ('WEAPON', 'Оружие'), ('AMULET', 'Амулет'), ('POTION', 'Зелье'), ('CONSUMABLE', 'Используемый предмет'), ('QUEST', 'Квестовый')], max_length=20, verbose_name='Тип предмета')),
                ('min_level_items', models.PositiveSmallIntegerField(default=1, verbose_name='Минимальный уровень продаваемых предметов')),
                ('max_level_items', models.PositiveSmallIntegerField(default=1, verbose_name='Максимальный уровень продаваемых предметов')),
            ],
        ),
    ]
