# Generated by Django 5.2.8 on 2025-11-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='item_type',
        ),
        migrations.AddField(
            model_name='shop',
            name='item_type_1',
            field=models.CharField(blank=True, choices=[('JUNK', 'Хлам'), ('RESOURCE', 'Ресурс'), ('ORE', 'Руда'), ('ARMOR', 'Броня'), ('WEAPON', 'Оружие'), ('AMULET', 'Амулет'), ('POTION', 'Зелье'), ('CONSUMABLE', 'Используемый предмет'), ('QUEST', 'Квестовый')], max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='item_type_2',
            field=models.CharField(blank=True, choices=[('JUNK', 'Хлам'), ('RESOURCE', 'Ресурс'), ('ORE', 'Руда'), ('ARMOR', 'Броня'), ('WEAPON', 'Оружие'), ('AMULET', 'Амулет'), ('POTION', 'Зелье'), ('CONSUMABLE', 'Используемый предмет'), ('QUEST', 'Квестовый')], max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='item_type_3',
            field=models.CharField(blank=True, choices=[('JUNK', 'Хлам'), ('RESOURCE', 'Ресурс'), ('ORE', 'Руда'), ('ARMOR', 'Броня'), ('WEAPON', 'Оружие'), ('AMULET', 'Амулет'), ('POTION', 'Зелье'), ('CONSUMABLE', 'Используемый предмет'), ('QUEST', 'Квестовый')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название магазина'),
        ),
    ]
