# Generated by Django 5.2.8 on 2025-11-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_shop_options_remove_shop_item_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylink',
            options={'default_related_name': 'activity_links'},
        ),
    ]
