# Generated by Django 5.2.8 on 2025-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_activitylink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylink',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
