# Generated by Django 5.2.8 on 2025-11-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('game', '0025_alter_activitylink_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylink',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
