# Generated by Django 5.2.8 on 2025-11-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_activitylink_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublocation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
