# Generated by Django 5.2.8 on 2025-11-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_sublocation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='item_slots_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='luck_bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
