# Generated by Django 5.2.8 on 2025-11-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_iteminstance_item_slots_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='item_type_1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='item_type_2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='item_type_3',
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_coef', models.PositiveSmallIntegerField(default=1, verbose_name='Коэффициент цены магазина')),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Предмет')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'предмет в магазине',
                'verbose_name_plural': 'Предметы в магазине',
                'unique_together': {('shop', 'item')},
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='allowed_items',
            field=models.ManyToManyField(blank=True, through='game.ShopItem', to='game.item', verbose_name='Доступные предметы'),
        ),
    ]
