# Generated by Django 5.2.8 on 2025-12-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_remove_shop_item_type_1_remove_shop_item_type_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterdrop',
            name='item',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.item'),
        ),
    ]
