# Generated by Django 5.2.8 on 2025-12-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_monsterdrop_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterdrop',
            name='item',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.CASCADE, to='game.item'),
            preserve_default=False,
        ),
    ]
